# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app/interface.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1800, 950)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1800, 950))
        MainWindow.setMaximumSize(QtCore.QSize(1800, 950))
        MainWindow.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setDocumentMode(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        self.browserButton = QtWidgets.QPushButton(self.centralwidget)
        self.browserButton.setGeometry(QtCore.QRect(390, 860, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.browserButton.setFont(font)
        self.browserButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.browserButton.setObjectName("browserButton")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(10, 0, 1791, 111))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.load_other_img = QtWidgets.QPushButton(self.centralwidget)
        self.load_other_img.setGeometry(QtCore.QRect(1300, 870, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.load_other_img.setFont(font)
        self.load_other_img.setObjectName("load_other_img")
        self.parameters = QtWidgets.QGroupBox(self.centralwidget)
        self.parameters.setGeometry(QtCore.QRect(1130, 140, 651, 681))
        self.parameters.setObjectName("parameters")
        self.grid_slider = QtWidgets.QSlider(self.parameters)
        self.grid_slider.setGeometry(QtCore.QRect(310, 90, 331, 31))
        self.grid_slider.setOrientation(QtCore.Qt.Horizontal)
        self.grid_slider.setObjectName("grid_slider")
        self.label = QtWidgets.QLabel(self.parameters)
        self.label.setGeometry(QtCore.QRect(30, 90, 251, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.parameters)
        self.label_2.setGeometry(QtCore.QRect(30, 160, 251, 31))
        self.label_2.setObjectName("label_2")
        self.grid_slider_2 = QtWidgets.QSlider(self.parameters)
        self.grid_slider_2.setGeometry(QtCore.QRect(310, 160, 331, 31))
        self.grid_slider_2.setOrientation(QtCore.Qt.Horizontal)
        self.grid_slider_2.setObjectName("grid_slider_2")
        self.grid_slider_3 = QtWidgets.QSlider(self.parameters)
        self.grid_slider_3.setGeometry(QtCore.QRect(310, 630, 331, 31))
        self.grid_slider_3.setOrientation(QtCore.Qt.Horizontal)
        self.grid_slider_3.setObjectName("grid_slider_3")
        self.label_3 = QtWidgets.QLabel(self.parameters)
        self.label_3.setGeometry(QtCore.QRect(30, 630, 271, 31))
        self.label_3.setObjectName("label_3")
        self.groupBox = QtWidgets.QGroupBox(self.parameters)
        self.groupBox.setGeometry(QtCore.QRect(30, 230, 601, 381))
        self.groupBox.setObjectName("groupBox")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(40, 70, 371, 51))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(40, 220, 371, 51))
        self.radioButton_2.setObjectName("radioButton_2")
        self.loaded_img = QtWidgets.QLabel(self.centralwidget)
        self.loaded_img.setGeometry(QtCore.QRect(170, 150, 931, 671))
        self.loaded_img.setObjectName("loaded_img")
        self.title.raise_()
        self.load_other_img.raise_()
        self.browserButton.raise_()
        self.parameters.raise_()
        self.loaded_img.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Application"))
        self.browserButton.setText(_translate("MainWindow", "Load an image"))
        self.title.setText(_translate("MainWindow", "Application de description du contenu des scènes réelles"))
        self.load_other_img.setText(_translate("MainWindow", "Load another image"))
        self.parameters.setTitle(_translate("MainWindow", "Parameters"))
        self.label.setText(_translate("MainWindow", "Grid step"))
        self.label_2.setText(_translate("MainWindow", "Padding (rho)"))
        self.label_3.setText(_translate("MainWindow", "Regularization factor K"))
        self.groupBox.setTitle(_translate("MainWindow", "Gradient"))
        self.radioButton.setText(_translate("MainWindow", "Sobel operator"))
        self.radioButton_2.setText(_translate("MainWindow", "Morphological gradient"))
        self.loaded_img.setText(_translate("MainWindow", "No image loaded"))

