# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1800, 950)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1800, 950))
        MainWindow.setMaximumSize(QtCore.QSize(1800, 950))
        MainWindow.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setDocumentMode(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        self.browserButton = QtWidgets.QPushButton(self.centralwidget)
        self.browserButton.setGeometry(QtCore.QRect(390, 860, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.browserButton.setFont(font)
        self.browserButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.browserButton.setObjectName("browserButton")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(10, 0, 1791, 111))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.load_other_img = QtWidgets.QPushButton(self.centralwidget)
        self.load_other_img.setGeometry(QtCore.QRect(390, 860, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.load_other_img.setFont(font)
        self.load_other_img.setObjectName("load_other_img")
        self.parameters = QtWidgets.QGroupBox(self.centralwidget)
        self.parameters.setGeometry(QtCore.QRect(1110, 110, 651, 711))
        self.parameters.setObjectName("parameters")
        self.grid_slider = QtWidgets.QSlider(self.parameters)
        self.grid_slider.setGeometry(QtCore.QRect(310, 60, 261, 31))
        self.grid_slider.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.grid_slider.setMinimum(5)
        self.grid_slider.setMaximum(100)
        self.grid_slider.setPageStep(1)
        self.grid_slider.setProperty("value", 10)
        self.grid_slider.setOrientation(QtCore.Qt.Horizontal)
        self.grid_slider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.grid_slider.setObjectName("grid_slider")
        self.label = QtWidgets.QLabel(self.parameters)
        self.label.setGeometry(QtCore.QRect(30, 60, 251, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.parameters)
        self.label_2.setGeometry(QtCore.QRect(30, 130, 251, 31))
        self.label_2.setObjectName("label_2")
        self.rho_slider = QtWidgets.QSlider(self.parameters)
        self.rho_slider.setGeometry(QtCore.QRect(310, 130, 261, 31))
        self.rho_slider.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.rho_slider.setMinimum(1)
        self.rho_slider.setMaximum(100)
        self.rho_slider.setPageStep(1)
        self.rho_slider.setProperty("value", 100)
        self.rho_slider.setSliderPosition(100)
        self.rho_slider.setOrientation(QtCore.Qt.Horizontal)
        self.rho_slider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.rho_slider.setObjectName("rho_slider")
        self.k_slider = QtWidgets.QSlider(self.parameters)
        self.k_slider.setGeometry(QtCore.QRect(310, 660, 261, 31))
        self.k_slider.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.k_slider.setPageStep(1)
        self.k_slider.setOrientation(QtCore.Qt.Horizontal)
        self.k_slider.setObjectName("k_slider")
        self.label_3 = QtWidgets.QLabel(self.parameters)
        self.label_3.setGeometry(QtCore.QRect(30, 660, 271, 31))
        self.label_3.setObjectName("label_3")
        self.grid_view = QtWidgets.QLabel(self.parameters)
        self.grid_view.setGeometry(QtCore.QRect(580, 60, 51, 31))
        self.grid_view.setAlignment(QtCore.Qt.AlignCenter)
        self.grid_view.setObjectName("grid_view")
        self.rho_view = QtWidgets.QLabel(self.parameters)
        self.rho_view.setGeometry(QtCore.QRect(580, 130, 51, 31))
        self.rho_view.setAlignment(QtCore.Qt.AlignCenter)
        self.rho_view.setObjectName("rho_view")
        self.k_view = QtWidgets.QLabel(self.parameters)
        self.k_view.setGeometry(QtCore.QRect(580, 660, 51, 31))
        self.k_view.setAlignment(QtCore.Qt.AlignCenter)
        self.k_view.setObjectName("k_view")
        self.std_text = QtWidgets.QLabel(self.parameters)
        self.std_text.setGeometry(QtCore.QRect(90, 400, 221, 31))
        self.std_text.setObjectName("std_text")
        self.kernel_size_slider = QtWidgets.QSlider(self.parameters)
        self.kernel_size_slider.setGeometry(QtCore.QRect(300, 270, 231, 31))
        self.kernel_size_slider.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.kernel_size_slider.setMinimum(2)
        self.kernel_size_slider.setMaximum(10)
        self.kernel_size_slider.setPageStep(1)
        self.kernel_size_slider.setProperty("value", 3)
        self.kernel_size_slider.setOrientation(QtCore.Qt.Horizontal)
        self.kernel_size_slider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.kernel_size_slider.setObjectName("kernel_size_slider")
        self.kernel_size_view = QtWidgets.QLabel(self.parameters)
        self.kernel_size_view.setGeometry(QtCore.QRect(540, 270, 51, 31))
        self.kernel_size_view.setAlignment(QtCore.Qt.AlignCenter)
        self.kernel_size_view.setObjectName("kernel_size_view")
        self.kernel_type = QtWidgets.QGroupBox(self.parameters)
        self.kernel_type.setGeometry(QtCore.QRect(80, 530, 531, 101))
        self.kernel_type.setObjectName("kernel_type")
        self.rect_3 = QtWidgets.QRadioButton(self.kernel_type)
        self.rect_3.setGeometry(QtCore.QRect(20, 40, 141, 51))
        self.rect_3.setChecked(True)
        self.rect_3.setObjectName("rect_3")
        self.cross_3 = QtWidgets.QRadioButton(self.kernel_type)
        self.cross_3.setGeometry(QtCore.QRect(410, 40, 101, 51))
        self.cross_3.setObjectName("cross_3")
        self.ellipse_3 = QtWidgets.QRadioButton(self.kernel_type)
        self.ellipse_3.setGeometry(QtCore.QRect(230, 40, 111, 51))
        self.ellipse_3.setObjectName("ellipse_3")
        self.std_view = QtWidgets.QLabel(self.parameters)
        self.std_view.setGeometry(QtCore.QRect(530, 400, 51, 31))
        self.std_view.setAlignment(QtCore.Qt.AlignCenter)
        self.std_view.setObjectName("std_view")
        self.kernel_size = QtWidgets.QLabel(self.parameters)
        self.kernel_size.setGeometry(QtCore.QRect(40, 270, 221, 31))
        self.kernel_size.setObjectName("kernel_size")
        self.std_slider = QtWidgets.QSlider(self.parameters)
        self.std_slider.setGeometry(QtCore.QRect(350, 400, 171, 31))
        self.std_slider.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.std_slider.setMinimum(0)
        self.std_slider.setMaximum(10)
        self.std_slider.setPageStep(1)
        self.std_slider.setProperty("value", 0)
        self.std_slider.setOrientation(QtCore.Qt.Horizontal)
        self.std_slider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.std_slider.setObjectName("std_slider")
        self.gradient_type = QtWidgets.QGroupBox(self.parameters)
        self.gradient_type.setGeometry(QtCore.QRect(20, 210, 611, 431))
        self.gradient_type.setObjectName("gradient_type")
        self.sobel_radio = QtWidgets.QRadioButton(self.gradient_type)
        self.sobel_radio.setGeometry(QtCore.QRect(20, 120, 371, 51))
        self.sobel_radio.setCheckable(True)
        self.sobel_radio.setChecked(True)
        self.sobel_radio.setObjectName("sobel_radio")
        self.morpho_radio = QtWidgets.QRadioButton(self.gradient_type)
        self.morpho_radio.setGeometry(QtCore.QRect(20, 240, 371, 51))
        self.morpho_radio.setAutoRepeat(False)
        self.morpho_radio.setObjectName("morpho_radio")
        self.gradient_type.raise_()
        self.kernel_size_view.raise_()
        self.kernel_type.raise_()
        self.kernel_size_slider.raise_()
        self.kernel_size.raise_()
        self.std_text.raise_()
        self.std_view.raise_()
        self.std_slider.raise_()
        self.grid_slider.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.rho_slider.raise_()
        self.k_slider.raise_()
        self.label_3.raise_()
        self.grid_view.raise_()
        self.rho_view.raise_()
        self.k_view.raise_()
        self.loaded_img = QtWidgets.QLabel(self.centralwidget)
        self.loaded_img.setGeometry(QtCore.QRect(30, 150, 1061, 671))
        self.loaded_img.setObjectName("loaded_img")
        self.apply_waterpixels = QtWidgets.QPushButton(self.centralwidget)
        self.apply_waterpixels.setGeometry(QtCore.QRect(1270, 860, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.apply_waterpixels.setFont(font)
        self.apply_waterpixels.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.apply_waterpixels.setObjectName("apply_waterpixels")
        self.visu = QtWidgets.QGroupBox(self.centralwidget)
        self.visu.setEnabled(True)
        self.visu.setGeometry(QtCore.QRect(440, 120, 651, 681))
        self.visu.setObjectName("visu")
        self.waterpixels = QtWidgets.QRadioButton(self.visu)
        self.waterpixels.setGeometry(QtCore.QRect(40, 570, 371, 51))
        self.waterpixels.setChecked(True)
        self.waterpixels.setObjectName("waterpixels")
        self.original = QtWidgets.QRadioButton(self.visu)
        self.original.setGeometry(QtCore.QRect(30, 200, 371, 51))
        self.original.setObjectName("original")
        self.original_2 = QtWidgets.QRadioButton(self.visu)
        self.original_2.setGeometry(QtCore.QRect(30, 80, 371, 51))
        self.original_2.setObjectName("original_2")
        self.original_3 = QtWidgets.QRadioButton(self.visu)
        self.original_3.setGeometry(QtCore.QRect(40, 440, 371, 51))
        self.original_3.setObjectName("original_3")
        self.original_4 = QtWidgets.QRadioButton(self.visu)
        self.original_4.setGeometry(QtCore.QRect(30, 310, 561, 61))
        self.original_4.setObjectName("original_4")
        self.title.raise_()
        self.load_other_img.raise_()
        self.browserButton.raise_()
        self.parameters.raise_()
        self.loaded_img.raise_()
        self.apply_waterpixels.raise_()
        self.visu.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Application"))
        self.browserButton.setText(_translate("MainWindow", "Load an image"))
        self.title.setText(_translate("MainWindow", "Waterpixels"))
        self.load_other_img.setText(_translate("MainWindow", "Load another image"))
        self.parameters.setTitle(_translate("MainWindow", "Parameters"))
        self.label.setText(_translate("MainWindow", "Grid step"))
        self.label_2.setText(_translate("MainWindow", "Padding (rho)"))
        self.label_3.setText(_translate("MainWindow", "Regularization factor K"))
        self.grid_view.setText(_translate("MainWindow", "0"))
        self.rho_view.setText(_translate("MainWindow", "0"))
        self.k_view.setText(_translate("MainWindow", "0"))
        self.std_text.setText(_translate("MainWindow", "Standard deviation"))
        self.kernel_size_view.setText(_translate("MainWindow", "0"))
        self.kernel_type.setTitle(_translate("MainWindow", "Kernel type"))
        self.rect_3.setText(_translate("MainWindow", "Rectangle"))
        self.cross_3.setText(_translate("MainWindow", "Cross"))
        self.ellipse_3.setText(_translate("MainWindow", "Ellipse"))
        self.std_view.setText(_translate("MainWindow", "0"))
        self.kernel_size.setText(_translate("MainWindow", "Kernel size"))
        self.gradient_type.setTitle(_translate("MainWindow", "Gradient"))
        self.sobel_radio.setText(_translate("MainWindow", "Sobel operator"))
        self.morpho_radio.setText(_translate("MainWindow", "Morphological gradient"))
        self.loaded_img.setText(_translate("MainWindow", "No image loaded"))
        self.apply_waterpixels.setText(_translate("MainWindow", "Apply Waterpixels"))
        self.visu.setTitle(_translate("MainWindow", "Vizualisation"))
        self.waterpixels.setText(_translate("MainWindow", "Waterpixels"))
        self.original.setText(_translate("MainWindow", "Gradient image"))
        self.original_2.setText(_translate("MainWindow", "Original image"))
        self.original_3.setText(_translate("MainWindow", "Voronoï Tesselations"))
        self.original_4.setText(_translate("MainWindow", "Original image with hexagonal grid"))

